### ISSUE TITLE
[Question] 无法按照教程进行文本分类，提示cudnn初始化失败

### ISSUE THREAD

**Issue by thehzzz** [BrikerMan/Kashgari#325]
## Environment

- OS [e.g. Mac OS, Linux]:ubuntu18.04
- Python Version:python3.6.9
- requirements.txt:  kashgari-tf,tensorflow-gpu==1.14，cuda==10.0，cudnn==7.4.1

```txt
[Paste requirements.txt file here]
```

## Question
按照官网教程[NLP - 15 分钟搭建中文文本分类模型](https://eliyar.biz/nlp_chinese_text_classification_in_15mins/)
我尝试了cuda==10.1，cudnn==7.6.2以及最后的cuda==10.0，cudnn==7.4.1，cudnn也不能初始化。

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/naldo/.local/lib/python3.6/site-packages/kashgari/tasks/base_model.py", line 310, in fit
    **fit_kwargs)
  File "/home/naldo/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/naldo/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/naldo/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/naldo/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/naldo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1d/conv1d}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1d/conv1d}}]]
         [[loss/mul/_85]]
0 successful operations.
0 derived errors ignored.

请问环境配置上有指定的版本要求吗？

**Comment by BrikerMan** [comment]
麻烦试试能不能在 colab 重现这个问题~

**Comment by thehzzz** [comment]
是cuda 和cudnn 版本问题，已经解决

**Comment by GaoQ1** [comment]
> 是cuda 和cudnn 版本问题，已经解决

能请问下kashgari==1.1.4对应的cuda和cudnn需要什么版本吗？

**Comment by yaleimeng** [comment]
@GaoQ1  其实搜索一下就能找到。这里 [版本对应关系](https://blog.csdn.net/fengdu78/article/details/104667044) 仅供参考。

**Comment by zacky1230** [comment]
@BrikerMan Ubuntu 18.04 + Python 3.6.9 + TensorFlow-GPU 1.14.0 + cuda 10.0 + cudnn 7.5.0 运行 报错 Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize，请教您的开发环境

**Comment by yaleimeng** [comment]
@zacky1230 你可能需要重新安装cudnn。最好是找个网络教程一步步跟着走。这都是环境问题，跟这个GitHub项目没关系。

**Comment by zacky1230** [comment]
@yaleimeng 试过不同版本的cudnn。检测都是正常的。
>>> from tensorflow.python.client import device_lib
>>> print(device_lib.list_local_devices())
2020-05-13 17:37:38.562719: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-13 17:37:38.584761: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-05-13 17:37:38.692449: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 17:37:38.692878: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4374060 executing computations on platform CUDA. Devices:
2020-05-13 17:37:38.692893: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2060 SUPER, Compute Capability 7.5
2020-05-13 17:37:38.711081: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3999845000 Hz
2020-05-13 17:37:38.711520: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x475b0d0 executing computations on platform Host. Devices:
2020-05-13 17:37:38.711547: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-05-13 17:37:38.711752: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 17:37:38.712323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2060 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2020-05-13 17:37:38.712529: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-05-13 17:37:38.713727: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-05-13 17:37:38.714736: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2020-05-13 17:37:38.715010: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2020-05-13 17:37:38.716463: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2020-05-13 17:37:38.717570: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2020-05-13 17:37:38.720987: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-05-13 17:37:38.721123: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 17:37:38.721765: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 17:37:38.722297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-05-13 17:37:38.722337: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-05-13 17:37:38.723344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-13 17:37:38.723362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2020-05-13 17:37:38.723369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2020-05-13 17:37:38.723495: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 17:37:38.724100: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-13 17:37:38.724655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 7098 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17395697523446708338
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 5268325951705173063
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 6774288851142056690
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 7443336397
locality {
  bus_id: 1
  links {
  }
}
incarnation: 2973702527088673731
physical_device_desc: "device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5"
]

**Comment by yaleimeng** [comment]
@zacky1230 贴这么多信息也无助于问题解决。别人没遇到过，当然就没法帮你。
提示cudnn无法初始化，不一定真的是cudnn的问题，也可以是它依赖的东西有问题。
但是这都是环境配置问题，跟这个项目没有什么直接关系。报错也不是这个项目的原因导致的。
虽然我会安装与配置，但没法面对面帮你解决。建议你把所有已经装好的卸载。按照别人的教程，从显卡驱动开始重新安装。确保各环节版本对应正确。环境配置是入门基本功，也许刚入门时碰巧顺利走过，但后面难免还是会栽跟头。早晚都要弄精通的。

**Comment by zacky1230** [comment]
@yaleimeng 谢谢您的建议。 这个问题我已经解决了。贴出我解决的方案：

import tensorflow as tf
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

参考（https://medium.com/@JeansPantRushi/fix-for-tensorflow-v2-failed-to-get-convolution-algorithm-b367a088b56e）
